### ISSUE TITLE
list.hbt is compiled to list/index.html

### ISSUE THREAD

**Issue by japboy** [techtribe/grunt-static-handlebars#3]
I got another issue.

`list.hbt` that includes `{{> _inc_partial}}` will be compiled to `list/index.html`. If `list.hbt` doesn't includes any partials, it will be compiled to `list.html`

I haven't found what exactly causes this though... Can you confirm this issue?

This is my settings and I use v0.6.0:

``` coffee
    staticHandlebars:
      options:
        partials : '<%= path.source %>/common/partials/*.hbp'
        json: '<%= path.source %>/meta.json'
      source:
        files:
          '<%= path.intermediate %>/**/*.html': '<%= path.source %>/**/*.hbt'
```

Thanks.

**Comment by techtribe** [comment]
It is not an issue, it is by design (for now).
- `list.hbt` without any partials is seen as a blank html file and just copied into the same-name file in the destination folder
- `list.hbt` with partials is seen as a template and looks for list.json (for extra context). if not found (and no issues arise with Handlebars rendering) it will use the setup of `list/index.html` while you can use `list/` as an URL
- json is an array now depending on the amount of templates you provide. To give all files 1 json did not have a use case before, but will look into it.

So add `list.json` (with {} as a basis) per file or use `list/index.html`

Does this provide information about why & how? ;)

PS: See current README.md for more information (updated this morning)

**Comment by japboy** [comment]
@Techtribe Ok. I personally prefer not to create another layer of directory, so it would be nice if there is an option for that.

Now I put `list.json` next to `list.hbt`, but it is compiled to `list/index.html`. Is this because of the design? Can I avoid this behaviour for now?

Thanks.

**Comment by techtribe** [comment]
Use `targetPath` inside your json and see this [example](https://github.com/Techtribe/grunt-static-handlebars/blob/master/test/fixtures/complex/contact/index.json).

Will that help? Do `grunt test` to see how it is used. I've updated the documentation.

**Comment by japboy** [comment]
Now I understand your philosophy more clearly. Sorry for taking your time.

I was actually looking for something like just a replacement of SSI `<!--#include virtual="./partial.html" -->` or PHP `<?php include('./partial.html'); ?>` because the server disallows to use them.

I need something more like simple. Perhaps putting JSON file every next to Handlebars template and wrapping them by directory is too verbose for my project. Maybe looking for another solution.

Thanks anyway :+1:

**Comment by techtribe** [comment]
It is a flexible separation between (chosen) context and markup. If you build an json-editor that only changes the json files, you will have a CMS. This plugin is to create easily new pages on top of other pages/templates without the problem of wrong headers or file-imports because that is offered as an integral feature.

So, good luck and thanks for the questions so I could update the documentation ;)
